name: Ansible Lint # feel free to pick your own name

on: [push, pull_request]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint@43e758bad47344f1ce7b699c0020299f486a8026
